### ISSUE TITLE
Exceptions / errors in dataproviders are not output

### ISSUE THREAD

**Issue by willemstuursma** [paratestphp/paratest#279]
If there is an exception in a data provider, paratest fails but the error is not shown. 

The output of paratest is:

```
FAILURES!
Tests: 11214, Assertions: 44655, Failures: 1, Errors: 0.
```

In PHPUnit, there is a warning and the warning _is_ shown:

```
There was 1 warning:

1) Warning
The data provider specified for myTest::testSomething is invalid.
Cannot access private const myclass::MY_CONST
```

**Comment by michaelbutler** [comment]
What version of paratest and PHPUnit are you running? I believe this quirk was fixed in the latest version(s). I just tested it like so:

```
michael@comp:~/PhpstormProjects/paratest_test_latest$ vendor/bin/phpunit test/
PHPUnit 6.4.3 by Sebastian Bergmann and contributors.

W                                                                   1 / 1 (100%)

Time: 13 ms, Memory: 4.00MB

There was 1 warning:

1) Warning
The data provider specified for Test1Test::stringsAreStrings is invalid.
Trying to invoke private method Test1Test::stringProvider() from scope ReflectionMethod

WARNINGS!
Tests: 1, Assertions: 0, Warnings: 1.
michael@comp:~/PhpstormProjects/paratest_test_latest$ echo $?
1
michael@comp:~/PhpstormProjects/paratest_test_latest$ vendor/bin/paratest -p4 test/

Running phpunit in 4 processes with /home/michael/PhpstormProjects/paratest_test_latest/vendor/bin/phpunit

Configuration read from /home/michael/PhpstormProjects/paratest_test_latest/phpunit.xml.dist

.W

Time: 55 ms, Memory: 4.00MB

There was 1 warning:

1) The data provider specified for Test1Test::stringsAreStrings is invalid.

FAILURES!
Tests: 1, Assertions: 0, Failures: 1, Errors: 0.
michael@comp:~/PhpstormProjects/paratest_test_latest$ echo $?
1
```

You can see that either running PHPUnit alone, or running with paratest, both generate the warning and show the result. They also both result in a `1` exit status code, indicating an error.

I do realize this was an issue in older versions, and as a work-around I created a global test listener for my test suite (see the PHPUnit documentation) and simply throw a `RuntimeException` when a warning occurs.

**Comment by Daanvm** [comment]
This is a bit of a late response, but we're still having this issue. We're using paratest version 2.2.0, because we're still using PHPUnit 7. I just confirmed that upgrading to paratest version 3.1.0 fixes this issue.

Note that this is not really limited to dataproviders. I was able to reproduce the same error by expecting a non-existing method to be called, like this:

```php
$mock = $this->createPartialMock(MyClass::class, []);
$mock
    ->expects($this->any())
    ->method('foobar');
```

With paratest 2.2.0 this results in the following output:

```
$ ./vendor/bin/paratest tests/

Running phpunit in 12 processes with /Users/daanvanmarsbergen/tmp/paratest/vendor/phpunit/phpunit/phpunit

Configuration read from /Users/daanvanmarsbergen/tmp/paratest/phpunit.xml.dist

.

Time: 229 ms, Memory: 4.00 MB


FAILURES!
Tests: 1, Assertions: 0, Failures: 1, Errors: 0.
```

With paratest 3.1.0 it works as expected:

```
$ ./vendor/bin/paratest tests/

Running phpunit in 12 processes with /Users/daanvanmarsbergen/tmp/paratest/vendor/phpunit/phpunit/phpunit

Configuration read from /Users/daanvanmarsbergen/tmp/paratest/phpunit.xml.dist

W

Time: 219 ms, Memory: 4.00 MB

There was 1 warning:

1) MyFirstTest::testParatest
Trying to configure method "foobar" which cannot be configured because it does not exist, has not been specified, is final, or is static

FAILURES!
Tests: 1, Assertions: 0, Failures: 1, Errors: 0.
```

**Comment by andreasschroth** [comment]
@Daanvm Thank you for your feedback. Unfortunately, we're not going to backport fixes due to limited time as it's "just" an OSS project. I'm sorry to not have better news regarding a backport. You might apply a patch manually to version 2.2.0 though.

Thus, I'll close this issue now.
