### ISSUE TITLE
Failing to run due to "This means a PHPUnit process has crashed"

### ISSUE THREAD

**Issue by Petah** [paratestphp/paratest#332]
I have a similar issue to #158, it seems that trying to run paratest fails, but slightly changing whats called (`vendor\bin\phpunit.bat` to `vendor\phpunit\phpunit\phpunit`) works fine:

```
C:\laravel>vendor\bin\paratest

Running phpunit in 5 processes with C:\laravel\vendor\bin\phpunit.bat

Configuration read from C:\laravel\phpunit.xml


In ResultPrinter.php line 198:

  Log file C:\Users\USER\AppData\Local\Temp\PT_5738.tmp is empty. This means a PHPUnit process has crashed.
  The process: c:\work\commands\php7\php.exe C:\laravel\vendor\bin\phpunit.bat --configuration C:\laravel\phpunit.xml --log-junit C:\Users\USER\AppData\Local\Temp\PT_5738.tmp Tests\Feature\Admin\AuthTest C:\laravel\tests\Feature\Admin\AuthTest.php
  This means a PHPUnit process was unable to run "C:\laravel\tests\Feature\Admin\AuthTest.php"
```

This works fine:

```
C:\work\laravel>c:\work\commands\php7\php.exe C:\work\laravel\vendor\phpunit\phpunit\phpunit --configuration C:\work\laravel\phpunit.xml --log-junit C:\Users\USER\AppData\Local\Temp\PT_5738.tmp Tests\Feature\Admin\AuthTest C:\work\laravel\tests\Feature\Admin\AuthTest.php
PHPUnit 7.2.7 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 193 ms, Memory: 12.00MB

OK (1 test, 1 assertion)
```

**Comment by andreasschroth** [comment]
Well, we have a PR open for that, I just don't really understand the underlying problem - any ideas here?

**Comment by andreasschroth** [comment]
I just merged PR #327 , this should fix the problem.

**Comment by joesaunderson** [comment]
@andreasschroth, I am still getting this message in version 1.*

What is the solution?

**Comment by andreasschroth** [comment]
@joesaunderson We don't actively support version 1.x anymore, sorry.

But it should work by backporting the changes here: https://github.com/paratestphp/paratest/pull/327/files

**Comment by joesaunderson** [comment]
@andreasschroth thanks for the reply.

I'm in an interesting position as phpunit-selenium 4.1.0 <= phpunit 6.5.15 <= paratest 1.*

Do you know of any better phpunit-selenium repositories that would allow me to update phpunit to a higher version?

**Comment by andreasschroth** [comment]
@joesaunderson I'm afraid not, sorry. We wrote our own adapter to Selenium back then when we used it together with PhpUnit.
